#!/usr/bin/env bash
# After rewrite events (e.g. `commit --amend`, `rebase`)
# If there is a rebase safety ref (i.e. there was a non-smooth conflict)
#   then, play victory music
git_dir="$(git rev-parse --git-dir)"
echo "aaaaaaAAAAA"
ls "$git_dir/rebase-apply"
ls "$git_dir/rebase-apply/abort-safety"
if test "$1" = "rebase" && test -f "$git_dir/rebase-apply/abort-safety"; then
  "$git_dir/hooks/play-victory.sh" "$git_dir/hooks/victory.mp3" &
fi
