#!/usr/bin/env bash
# On merge conflict actions (e.g. fighting merge conflicts)
# DEV: We use a placeholder file because as of git@2, there is no long "Conflicts:" in the `git log`
git_dir="$(git rev-parse --git-dir)"
victory_occurred_filepath="$git_dir/__victory_occurred"
if test -f "$victory_occurred_filepath"; then
  # Play fanfare
  fanfare="$git_dir/hooks/victory.mp3"
  if which afplay &> /dev/null; then
    afplay -v 5 "$fanfare"
  elif which mplayer &> /dev/null; then
    mplayer "$fanfare" &> /dev/null &
  else
    echo "No player found for \`victory.mp3\` playback =(" 1>&2
  fi
fi
