#!/usr/bin/env bash
# If we are about to complete a merge, save a placeholder file
# https://github.com/twolfson/sexy-bash-prompt/blob/0.26.1/.bash_prompt#L112-L118
git_dir="$(git rev-parse --git-dir)"
victory_occurred_filepath="$git_dir/__victory_occurred"
if test -f "$git_dir/MERGE_HEAD"; then
  touch "$victory_occurred_filepath"
# Otherwise, wipe out our placeholder file (in case it was there from earlier)
elif test -f "$victory_occurred_filepath"; then
  rm "$victory_occurred_filepath" &> /dev/null
fi
