language: bash
sudo: true # Require sudo for `apt` customization
env:
  - GIT_VERSION="1.7" # Ubuntu Precise stable
  - GIT_VERSION="1.8" # Default `git` provided by Travis CI
  - GIT_VERSION="2.x" # git@2.x

before_script:
  - bin/travis-setup.sh # Take care of git version
  - apt-cache policy git # Determine git PPA source
  - git --version # Spit out the git version
script:
  # Run our tests
  - test/index.sh

notifications:
  email: false
